drop table if exists time;
CREATE TABLE if not exists time
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "current_data" VARCHAR(50),
    CONSTRAINT pk_time PRIMARY KEY (id)
);